services:
    doctrine.website.directive.warning:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\WarningDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.caution:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\CautionDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.tip:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\TipDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.configuration_block:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\ConfigurationBlockDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.section_author:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\SectionAuthorDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.version_added:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\VersionAddedDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.role:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\RoleDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.index:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\IndexDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.hint:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\HintDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.notice:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\NoticeDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.note:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\NoteDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.toc:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\TocDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]

    doctrine.website.directive.toc_header:
        public: false
        class: Doctrine\Website\DoctrineSculpinBundle\Directive\TocHeaderDirective
        arguments: []
        tags: [{ name: doctrine.rst.directive }]
