imports:
    - { resource: local.yml }
    - { resource: projects.yml }
    - { resource: team_members.yml }

sculpin_content_types:
    posts:
        type: path
        path: _posts
        permalink: :year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories

sculpin_twig:
    source_view_paths: ['_views', '_layouts', '_partials', '_includes']
    extensions: ['', 'twig', 'html', 'html.twig', 'twig.html', 'rst']

services:
    doctrine.twig.main.extension:
        class: Doctrine\Website\Twig\MainExtension
        public: false
        arguments:
            - '%doctrine.team_members%'
        tags:
            - { name: twig.extension }

    doctrine.twig.project.extension:
        class: Doctrine\Website\Twig\ProjectExtension
        public: false
        arguments:
            - '@doctrine.project.repository'
        tags:
            - { name: twig.extension }

    doctrine.project.factory:
        class: Doctrine\Website\Projects\ProjectFactory
        public: false

    doctrine.process.factory:
        class: Doctrine\Website\ProcessFactory
        public: false

    doctrine.project.repository:
        class: Doctrine\Website\Projects\ProjectRepository
        public: false
        arguments:
            - '%doctrine.projects%'
            - '@doctrine.project.factory'

    doctrine.project.git_syncer:
        class: Doctrine\Website\Projects\ProjectGitSyncer
        public: false
        arguments:
            - '@doctrine.process.factory'
            - '%doctrine.projects_path%'

    doctrine.search.algolia_client:
        class: AlgoliaSearch\Client
        public: false
        arguments:
            - '%doctrine.search.algolia.application_id%'
            - '%doctrine.search.algolia.admin_api_key%'

    doctrine.search.indexer:
        class: Doctrine\Website\Docs\SearchIndexer
        public: false
        arguments:
            - '@doctrine.search.algolia_client'
            - '@doctrine.docs.rst_builder'

    doctrine.rst.kernel.html:
        class: Gregwar\RST\HTML\Kernel
        public: false

    doctrine.rst.kernel:
        class: Doctrine\Website\RST\Kernel
        public: false
        arguments:
            - @doctrine.rst.kernel.html
            - []

    doctrine.rst.builder:
        class: Gregwar\RST\Builder
        public: false
        arguments:
            - '@doctrine.rst.kernel'

    doctrine.docs.api_builder:
        class: Doctrine\Website\Docs\APIBuilder
        public: false
        arguments:
            - '@doctrine.process.factory'
            - '%doctrine.projects_path%'
            - '%doctrine.sculpin_source_path%'

    doctrine.docs.rst_builder:
        class: Doctrine\Website\Docs\RSTBuilder
        arguments:
            - '%doctrine.sculpin_source_path%'
            - '@doctrine.rst.builder'
            - '%doctrine.projects_path%'

    doctrine.docs.build_docs:
        class: Doctrine\Website\Docs\BuildDocs
        public: true
        arguments:
            - '@doctrine.project.repository'
            - '@doctrine.project.git_syncer'
            - '@doctrine.docs.api_builder'
            - '@doctrine.docs.rst_builder'
            - '@doctrine.search.indexer'

    doctrine.website_builder:
        class: Doctrine\Website\WebsiteBuilder
        public: true
        arguments:
            - '@doctrine.process.factory'
            - '@sculpin.site_configuration'
            - '%kernel.root_dir%'

    doctrine.watcher:
        class: Doctrine\Website\Watcher
        public: true
        arguments:
            - '@doctrine.process.factory'
            - '%kernel.root_dir%'

    doctrine.deployer:
        class: Doctrine\Website\Deployer
        public: true
        arguments:
            - '@doctrine.process.factory'
            - '%doctrine.projects_path%'
            - '%kernel.environment%'

parameters:
    doctrine.sculpin_source_path: '%kernel.root_dir%/../source'

    doctrine.search.algolia.application_id: YVYTFT9XMW
    doctrine.search.algolia.index: pages
