parameters:
    doctrine.website.algolia.app_id: 'YVYTFT9XMW'
    doctrine.website.algolia.admin_api_key: '1234'

    doctrine.website.projects_path: '%doctrine.website.root_dir%/projects'
    doctrine.website.docs_path: '%doctrine.website.root_dir%/docs'
    doctrine.website.source_path: '%doctrine.website.root_dir%/source'
    doctrine.website.webpack_build_path: '%doctrine.website.root_dir%/.webpack-build'
    doctrine.website.templates_path: '%doctrine.website.root_dir%/templates'

    doctrine.website.title: Doctrine
    doctrine.website.subtitle: PHP Database Tools
    doctrine.website.url: http://lcl.doctrine-project.org:8080
    doctrine.website.keywords: [php, mysql, orm, dbal, database, mongodb, odm, annotations, migrations, cache, couchdb]
    doctrine.website.description: >
        The Doctrine Project is the home to several PHP libraries primarily
        focused on database storage and object mapping. The core projects
        are the Object Relational Mapper (ORM) and the Database Abstraction
        Layer (DBAL) it is built upon.
    doctrine.website.google_analytics_tracking_id: ''

    doctrine.website.doctrine_users:
        -
            name: Symfony
            url: https://symfony.com/
        -
            name: Drupal
            url: https://www.drupal.org/
        -
            name: Laravel
            url: https://laravel.com/
        -
            name: JMS Libraries
            url: https://jmsyst.com/
        -
            name: Go! AOP
            url: https://go.aopphp.com/
        -
            name: KNP Labs
            url: https://knplabs.com/
        -
            name: eZ Platform
            url: https://www.ezplatform.com/
        -
            name: API Platform
            url: https://api-platform.com/
        -
            name: PrestaShop
            url: https://www.prestashop.com/en
        -
            name: PHPUnit
            url: https://phpunit.de/
        -
            name: Prophecy
            url: https://github.com/phpspec/prophecy
        -
            name: phpbench
            url: https://github.com/phpbench/phpbench
        -
            name: TYPO3
            url: https://typo3.org/
        -
            name: Sonata Project
            url: https://sonata-project.org/
