parameters:
    doctrine.website.project_integration.types:
        symfony:
            name: Symfony
            url: https://symfony.com
            icon: https://symfony.com/logos/symfony_black_03.png

    doctrine.website.projects_data:
        -
            repositoryName: orm

        -
            repositoryName: dbal

        -
            repositoryName: mongodb-odm

        -
            repositoryName: phpcr-odm

        -
            repositoryName: couchdb-odm

        -
            repositoryName: migrations

        -
            repositoryName: common

        -
            repositoryName: mongodb

        -
            repositoryName: orientdb-odm

        -
            repositoryName: annotations

        -
            repositoryName: collections

        -
            repositoryName: inflector

        -
            repositoryName: cache

        -
            repositoryName: lexer

        -
            repositoryName: event-manager

        -
            repositoryName: persistence

        -
            repositoryName: reflection

        -
            repositoryName: coding-standard

        -
            repositoryName: doctrine1

        -
            repositoryName: instantiator

        -
            repositoryName: rst-parser

        -
            repositoryName: couchdb-client

        -
            repositoryName: skeleton-mapper

        -
            repositoryName: DoctrineBundle
            integration: true
            integrationFor: orm
            integrationType: symfony

        -
            repositoryName: DoctrineCacheBundle
            integration: true
            integrationFor: cache
            integrationType: symfony

        -
            repositoryName: DoctrineMigrationsBundle
            integration: true
            integrationFor: migrations
            integrationType: symfony

        -
            repositoryName: DoctrineMongoDBBundle
            slug: doctrine-mongodb-bundle
            integration: true
            integrationFor: mongodb-odm
            integrationType: symfony
