
name: "Coding Standards"

on: ["pull_request", "push"]

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@13.1.0"
    with:
      php-version: "8.5"
      composer-dependency-versions: "locked"
